language: scala
sudo: false

scala:
  - 2.11.11

jdk:
  - oraclejdk8

#deploy:
#  provider: releases
#  api_key: ""
#  file_glob: true
#  file: "target/universal/pg2bq-*.zip"
#  skip_cleanup: true
#  on:
#    tags: true

before_install:
  # travis sets the java options which breaks tests that check the applied memory settings
  - unset _JAVA_OPTIONS
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install xz;
      brew install sbt;
    fi

script: sbt clean universal:packageBin

